//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkoulaACDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcdfCategory
    {
        public AcdfCategory()
        {
            this.AcdfSubCategories = new HashSet<AcdfSubCategory>();
        }
    
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
    
        public virtual ICollection<AcdfSubCategory> AcdfSubCategories { get; set; }
    }
}
