//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IkoulaACDF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AspNetUser
    {
        public AspNetUser()
        {
            this.AcdfGuessBooks = new HashSet<AcdfGuessBook>();
        }
    
        public string Id { get; set; }
        public string UserName { get; set; }
        public string PasswordHash { get; set; }
        public string SecurityStamp { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public Nullable<int> FirstYearSchool { get; set; }
        public Nullable<int> LastYearSchool { get; set; }
        public string LastClass { get; set; }
        public string ActualCity { get; set; }
        public string ActualCountry { get; set; }
        public string PhotoUrl { get; set; }
        public string Discriminator { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
    
        public virtual ICollection<AcdfGuessBook> AcdfGuessBooks { get; set; }
    }
}
